language: objective-c
podfile: Example/Podfile

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i xcpretty  --no-ri --no-rdoc

xcode_workspace: Example/SKSpinner.xcworkspace
xcode_scheme: SKSpinner-Example
xcode_sdk: iphonesimulator
